public class ApexLearning01 {
    // apex only run in sandbox environment
    // or developer org,nit in production
    
    /**public ApexLearning01(){
        //system.debug is used to print statement
        //All the diplay text are in single quets ''
        System.debug('I am constructor');
    }*/
    Boolean b=True;
    public void MethodDemo(){
        System.debug('I am method');
		System.debug('b ='+b);

    }
}