public class ApexLearningSet {
    Public Void Set01(){
        Set<String> str=New Set<String>();
        
        str.add('A');
        str.add('A');
        //str.addAll()													
        //.clear()
        //.clone()
        //.contains
        //set.containsAll(set or list) it compare set to list or set
        //.equals
        //.isEmpty()
        //.remove('') , str.removeAll(str1)
        //str.retainAll(str1) opposite of remove , bracket la irukura value matum tha kamikum 
        System.debug('str '+str);
    }

}